chaos:
  monkey:
    assaults:
      latencyActive: true
      level: 1
      exceptionsActive: true
      killApplicationActive: true
    watcher:
      repository: true
      restController: true
      service: true
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        # include all endpoints
        include: "*"
spring:
  profiles:
    active: chaos-monkey
