chaos:
  monkey:
    assaults:
      latencyActive: true
      level: 1
      exceptionsActive: true
      killApplicationActive: true
    watcher:
      repository: true
      restController: true
      service: true